// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b71178bd-aa23-44be-beea-47be320c932d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onChDownChange();
void onChUpChange();
void onTvStatusChange();
void onVolDownChange();
void onVolUpChange();

bool ch_down;
bool ch_up;
bool tv_status;
bool vol_down;
bool vol_up;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ch_down, READWRITE, ON_CHANGE, onChDownChange);
  ArduinoCloud.addProperty(ch_up, READWRITE, ON_CHANGE, onChUpChange);
  ArduinoCloud.addProperty(tv_status, READWRITE, ON_CHANGE, onTvStatusChange);
  ArduinoCloud.addProperty(vol_down, READWRITE, ON_CHANGE, onVolDownChange);
  ArduinoCloud.addProperty(vol_up, READWRITE, ON_CHANGE, onVolUpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
