#include "arduino_secrets.h"
#include "IRremote.h"
#include "thingProperties.h"
#include "Arduino.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "WiFi Cloud TV Remote"
  https://create.arduino.cc/cloud/things/d8d7b6c3-a36c-4cb3-8dd3-3839d0522448 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool ch_down;
  bool ch_up;
  bool tv_status;
  bool vol_down;
  bool vol_up;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

IRsend irsend;

const int irrecvpin = 5  //GPIO5 pin = D1 on NodeMCU. Use only pins with PWM enabled.

void setup() 
{
  int i;
  
  Serial.begin(115200);
  irsend.begin(irrecvpin);
  
  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);  //Debug message display on Serial monitor
  ArduinoCloud.printDebugInfo();
  
  Serial.println("-----------------------------------------------");
  Serial.println("\t!! Initialising !!");
  Serial.println("-----------------------------------------------");
  
  pinMode(irrecvpin, OUTPUT);
  for(i=0; i<10; i++)
  {
    digitalWrite(irrecvpin, HIGH);
    delay(100);
    digitalWrite(irrecvpin, LOW);
    delay(100);
    Serial.println(".");
  }
  Serial.println("-----------------------------------------------");
  Serial.println("\t!! Starting Transmission !!");
  Serial.println("-----------------------------------------------");
}

void loop() 
{
  ArduinoCloud.update();
}

void onTvStatusChange()  
{
  if(tv_status)
  {
    irsend.sendNECRaw(0x40BFA05F, 3);
    Serial.println("Sent TV On signal");
    delay(100);
  }
}

void onVolUpChange()  
{
  if(vol_up)
  {
    irsend.sendNECRaw(0x11D98E71, 3);
    Serial.println("Sent Volume Up signal");
    delay(100);
  }
}

void onVolDownChange()  
{
  if(vol_down)
  {
    irsend.sendNECRaw(0x11D94EB1, 3);
    Serial.println("Sent Volume Down signal");
    delay(100);
  }
}

void onChUpChange()  
{
  if(ch_up)
  {
    irsend.sendNCERaw(0x11D9CE31, 3);
    Serial.println("Sent Channel Up signal");
    delay(100);
  }
}

void onChDownChange()  
{
  if(ch_down)
  {
    irsend.sendNECRaw(0x11D92ED1, 3);
    Serial.println("Sent Channel Down signal");
    delay(100);
  }
}
